name: base

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python=3.6
  - numpy >=1.11.0
  - iris >=2.1.0
  - xarray >=0.10.8
  - pandas >=0.22.0
  - cartopy >=0.16.0
  - numpy >=1.14
  - matplotlib =2.2.*
  - seaborn >=0.8.1
  - geopy >=1.17.0
  - basemap
  - netcdf4
  - cis
  - jupyter
  - ipykernel
  - notebook >=5.6.0
  - llvmlite
  - cython
  - numba
  - scipy
  - scikit-learn
  - jupyterlab
  - nc-time-axis
  - PyTables
  - xlrd
  - ipyleaflet=0.9.2
  - rasterio
  - tqdm
  - requests
  - pillow
  - branca
  - geopandas
  - voila
  - nodejs
  - pythreejs
  - bqplot

